src/main/java/br/edu/ifsc/loja/model/Usuario.java
package br.edu.ifsc.loja.model;

import java.util.Date;

public class Usuario extends BaseEntity {
	
	private Long id;
	
	private String login;
	
	private String senha;
	
	private String nome;
	
	private String cpf;
	
	private Date dataCadastro;
	
	public Usuario(){
		this.cpf = "";
		this.senha = "";
		this.dataCadastro = new Date();
		this.id = -1L;
		this.login = "";
		this.nome = "";
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public Long getId() {
		return this.id;
	}

	@Override
	public void setId(Long id) {
		this.id = id;
	}
	
	 @Override
	public String toString() {
		 return this.nome;
	}
	 
	public boolean equals(Usuario usuario) {
		return usuario.id.equals(this.id);
	}
	
	public Date getDataCastro(){
		return this.dataCadastro;
	}

}

src/main/java/br/edu/ifsc/loja/controller/UsuarioController.java
package br.edu.ifsc.loja.controller;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;

import br.edu.ifsc.loja.dao.UsuarioDAO;
import br.edu.ifsc.loja.model.Usuario;

public class UsuarioController implements Controller {

	@Override
	public String executa(HttpServletRequest req, HttpServletResponse response) {
		String action = req.getParameter("action");
		String pagina ="/index.jsp";
		if (!StringUtils.isEmpty(action)){
			switch (action) {
			case "lista":
				  pagina = lista(req);
				break;
			case "novo":
				  pagina = novo(req);
				break;
			}
		}
		return pagina;
		
	}

	private String novo(HttpServletRequest req) {
		Usuario usuario = new Usuario();
		usuario.setNome(req.getParameter("nome"));
		usuario.setCpf(req.getParameter("cpf"));
		usuario.setLogin(req.getParameter("login"));
		usuario.setSenha(req.getParameter("senha"));
		
		UsuarioDAO.getInstance().insert(usuario);
		
		return "/index.jsp";
	}

	private String lista(HttpServletRequest req){
		List<Usuario> usuarios = UsuarioDAO.getInstance().all();
		req.setAttribute("usuarios", usuarios);
		return "/WEB-INF/jsp/usuario/usuario.jsp";
	}
}

src/main/webapp/WEB-INF/jsp/usuario/usuario.jsp
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="loja" tagdir="/WEB-INF/tags" %>

<c:import url="/WEB-INF/jsp/header.jsp" />

	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<strong><f:message key="name"/></strong>
			</div>
			<div class="col-md-3">
				<strong><f:message key="social_security_number"/></strong>
			</div>
			<div class="col-md-3">
				<strong><f:message key="login"/></strong>
			</div>
			<div class="col-md-3">
				<strong><f:message key="date_of_registration"/></strong>
			</div>
		</div>
		<c:forEach items="${usuarios}" var="usuario">
			<div class="row">
				<div class="col-md-3">${usuario.nome}</div>
				<div class="col-md-3">${usuario.cpf}</div>
				<div class="col-md-3">${usuario.login}</div>
				<div class="col-md-3">
					<f:formatDate pattern="dd/MM/yyyy hh:mm"
						value="${usuario.dataCastro}" />
				</div>
			</div>
		</c:forEach>
	</div>
	<c:import url="/WEB-INF/jsp/footer.jsp" />